<?php
/**
 * CitationIntelligenceApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LLMPulse\ApiException;
use LLMPulse\Configuration;
use LLMPulse\FormDataProcessor;
use LLMPulse\HeaderSelector;
use LLMPulse\ObjectSerializer;

/**
 * CitationIntelligenceApi Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CitationIntelligenceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getCitedUrlContent' => [
            'application/json',
        ],
        'getCitedUrlDetail' => [
            'application/json',
        ],
        'getMentionsByCitingDomain' => [
            'application/json',
        ],
        'listCitationGroups' => [
            'application/json',
        ],
        'listCitedUrlOccurrences' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getCitedUrlContent
     *
     * Cited URL cached content
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlContent'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getCitedUrlContent($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlContent'][0])
    {
        $this->getCitedUrlContentWithHttpInfo($project_id, $url_sha256, $contentType);
    }

    /**
     * Operation getCitedUrlContentWithHttpInfo
     *
     * Cited URL cached content
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlContent'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCitedUrlContentWithHttpInfo($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlContent'][0])
    {
        $request = $this->getCitedUrlContentRequest($project_id, $url_sha256, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LLMPulse\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCitedUrlContentAsync
     *
     * Cited URL cached content
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCitedUrlContentAsync($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlContent'][0])
    {
        return $this->getCitedUrlContentAsyncWithHttpInfo($project_id, $url_sha256, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCitedUrlContentAsyncWithHttpInfo
     *
     * Cited URL cached content
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCitedUrlContentAsyncWithHttpInfo($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlContent'][0])
    {
        $returnType = '';
        $request = $this->getCitedUrlContentRequest($project_id, $url_sha256, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCitedUrlContent'
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlContent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCitedUrlContentRequest($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlContent'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getCitedUrlContent'
            );
        }

        // verify the required parameter 'url_sha256' is set
        if ($url_sha256 === null || (is_array($url_sha256) && count($url_sha256) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url_sha256 when calling getCitedUrlContent'
            );
        }
        if (!preg_match("/^[a-f0-9]{64}$/", $url_sha256)) {
            throw new \InvalidArgumentException("invalid value for \"url_sha256\" when calling CitationIntelligenceApi.getCitedUrlContent, must conform to the pattern /^[a-f0-9]{64}$/.");
        }
        

        $resourcePath = '/citation_intelligence/urls/{url_sha256}/content';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($url_sha256 !== null) {
            $resourcePath = str_replace(
                '{url_sha256}',
                ObjectSerializer::toPathValue($url_sha256),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCitedUrlDetail
     *
     * Cited URL detail
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlDetail'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getCitedUrlDetail($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlDetail'][0])
    {
        $this->getCitedUrlDetailWithHttpInfo($project_id, $url_sha256, $contentType);
    }

    /**
     * Operation getCitedUrlDetailWithHttpInfo
     *
     * Cited URL detail
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlDetail'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCitedUrlDetailWithHttpInfo($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlDetail'][0])
    {
        $request = $this->getCitedUrlDetailRequest($project_id, $url_sha256, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LLMPulse\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCitedUrlDetailAsync
     *
     * Cited URL detail
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlDetail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCitedUrlDetailAsync($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlDetail'][0])
    {
        return $this->getCitedUrlDetailAsyncWithHttpInfo($project_id, $url_sha256, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCitedUrlDetailAsyncWithHttpInfo
     *
     * Cited URL detail
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlDetail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCitedUrlDetailAsyncWithHttpInfo($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlDetail'][0])
    {
        $returnType = '';
        $request = $this->getCitedUrlDetailRequest($project_id, $url_sha256, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCitedUrlDetail'
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCitedUrlDetail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCitedUrlDetailRequest($project_id, $url_sha256, string $contentType = self::contentTypes['getCitedUrlDetail'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getCitedUrlDetail'
            );
        }

        // verify the required parameter 'url_sha256' is set
        if ($url_sha256 === null || (is_array($url_sha256) && count($url_sha256) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url_sha256 when calling getCitedUrlDetail'
            );
        }
        if (!preg_match("/^[a-f0-9]{64}$/", $url_sha256)) {
            throw new \InvalidArgumentException("invalid value for \"url_sha256\" when calling CitationIntelligenceApi.getCitedUrlDetail, must conform to the pattern /^[a-f0-9]{64}$/.");
        }
        

        $resourcePath = '/citation_intelligence/urls/{url_sha256}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($url_sha256 !== null) {
            $resourcePath = str_replace(
                '{url_sha256}',
                ObjectSerializer::toPathValue($url_sha256),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMentionsByCitingDomain
     *
     * Mention share by citing domain
     *
     * @param  int $project_id Project ID (required)
     * @param  string[] $domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from from (optional)
     * @param  \DateTime|null $to to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMentionsByCitingDomain'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getMentionsByCitingDomain($project_id, $domains, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, string $contentType = self::contentTypes['getMentionsByCitingDomain'][0])
    {
        $this->getMentionsByCitingDomainWithHttpInfo($project_id, $domains, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $contentType);
    }

    /**
     * Operation getMentionsByCitingDomainWithHttpInfo
     *
     * Mention share by citing domain
     *
     * @param  int $project_id Project ID (required)
     * @param  string[] $domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMentionsByCitingDomain'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMentionsByCitingDomainWithHttpInfo($project_id, $domains, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, string $contentType = self::contentTypes['getMentionsByCitingDomain'][0])
    {
        $request = $this->getMentionsByCitingDomainRequest($project_id, $domains, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LLMPulse\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMentionsByCitingDomainAsync
     *
     * Mention share by citing domain
     *
     * @param  int $project_id Project ID (required)
     * @param  string[] $domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMentionsByCitingDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMentionsByCitingDomainAsync($project_id, $domains, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, string $contentType = self::contentTypes['getMentionsByCitingDomain'][0])
    {
        return $this->getMentionsByCitingDomainAsyncWithHttpInfo($project_id, $domains, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMentionsByCitingDomainAsyncWithHttpInfo
     *
     * Mention share by citing domain
     *
     * @param  int $project_id Project ID (required)
     * @param  string[] $domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMentionsByCitingDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMentionsByCitingDomainAsyncWithHttpInfo($project_id, $domains, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, string $contentType = self::contentTypes['getMentionsByCitingDomain'][0])
    {
        $returnType = '';
        $request = $this->getMentionsByCitingDomainRequest($project_id, $domains, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMentionsByCitingDomain'
     *
     * @param  int $project_id Project ID (required)
     * @param  string[] $domains Source domains to analyze, e.g. domains[]&#x3D;gmac.com&amp;domains[]&#x3D;educaweb.com (required)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMentionsByCitingDomain'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMentionsByCitingDomainRequest($project_id, $domains, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, string $contentType = self::contentTypes['getMentionsByCitingDomain'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getMentionsByCitingDomain'
            );
        }

        // verify the required parameter 'domains' is set
        if ($domains === null || (is_array($domains) && count($domains) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domains when calling getMentionsByCitingDomain'
            );
        }









        $resourcePath = '/citation_intelligence/mentions_by_domain';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $domains,
            'domains', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $model,
            'model', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $collection_id,
            'collection_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country_code,
            'country_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language_code,
            'language_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prompt,
            'prompt', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCitationGroups
     *
     * Grouped citation intelligence
     *
     * @param  int $project_id Project ID (required)
     * @param  string|null $view view (optional, default to 'url')
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $per_page per_page (optional, default to 20)
     * @param  string|null $order order (optional)
     * @param  string|null $direction direction (optional)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from from (optional)
     * @param  \DateTime|null $to to (optional)
     * @param  string|null $query query (optional)
     * @param  string|null $source_type source_type (optional)
     * @param  string|null $sentiment sentiment (optional)
     * @param  string|null $content_gap content_gap (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitationGroups'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function listCitationGroups($project_id, $view = 'url', $page = 1, $per_page = 20, $order = null, $direction = null, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, $query = null, $source_type = null, $sentiment = null, $content_gap = null, string $contentType = self::contentTypes['listCitationGroups'][0])
    {
        $this->listCitationGroupsWithHttpInfo($project_id, $view, $page, $per_page, $order, $direction, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $query, $source_type, $sentiment, $content_gap, $contentType);
    }

    /**
     * Operation listCitationGroupsWithHttpInfo
     *
     * Grouped citation intelligence
     *
     * @param  int $project_id Project ID (required)
     * @param  string|null $view (optional, default to 'url')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string|null $order (optional)
     * @param  string|null $direction (optional)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $query (optional)
     * @param  string|null $source_type (optional)
     * @param  string|null $sentiment (optional)
     * @param  string|null $content_gap (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitationGroups'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCitationGroupsWithHttpInfo($project_id, $view = 'url', $page = 1, $per_page = 20, $order = null, $direction = null, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, $query = null, $source_type = null, $sentiment = null, $content_gap = null, string $contentType = self::contentTypes['listCitationGroups'][0])
    {
        $request = $this->listCitationGroupsRequest($project_id, $view, $page, $per_page, $order, $direction, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $query, $source_type, $sentiment, $content_gap, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LLMPulse\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCitationGroupsAsync
     *
     * Grouped citation intelligence
     *
     * @param  int $project_id Project ID (required)
     * @param  string|null $view (optional, default to 'url')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string|null $order (optional)
     * @param  string|null $direction (optional)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $query (optional)
     * @param  string|null $source_type (optional)
     * @param  string|null $sentiment (optional)
     * @param  string|null $content_gap (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitationGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitationGroupsAsync($project_id, $view = 'url', $page = 1, $per_page = 20, $order = null, $direction = null, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, $query = null, $source_type = null, $sentiment = null, $content_gap = null, string $contentType = self::contentTypes['listCitationGroups'][0])
    {
        return $this->listCitationGroupsAsyncWithHttpInfo($project_id, $view, $page, $per_page, $order, $direction, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $query, $source_type, $sentiment, $content_gap, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCitationGroupsAsyncWithHttpInfo
     *
     * Grouped citation intelligence
     *
     * @param  int $project_id Project ID (required)
     * @param  string|null $view (optional, default to 'url')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string|null $order (optional)
     * @param  string|null $direction (optional)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $query (optional)
     * @param  string|null $source_type (optional)
     * @param  string|null $sentiment (optional)
     * @param  string|null $content_gap (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitationGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitationGroupsAsyncWithHttpInfo($project_id, $view = 'url', $page = 1, $per_page = 20, $order = null, $direction = null, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, $query = null, $source_type = null, $sentiment = null, $content_gap = null, string $contentType = self::contentTypes['listCitationGroups'][0])
    {
        $returnType = '';
        $request = $this->listCitationGroupsRequest($project_id, $view, $page, $per_page, $order, $direction, $model, $collection_id, $country_code, $language_code, $prompt, $from, $to, $query, $source_type, $sentiment, $content_gap, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCitationGroups'
     *
     * @param  int $project_id Project ID (required)
     * @param  string|null $view (optional, default to 'url')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string|null $order (optional)
     * @param  string|null $direction (optional)
     * @param  string|null $model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param  int|null $collection_id (optional)
     * @param  string|null $country_code ISO country code (e.g. US, GB, DE) (optional)
     * @param  string|null $language_code ISO language code (e.g. en, es, de) (optional)
     * @param  int|null $prompt Filter by prompt ID (optional)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $query (optional)
     * @param  string|null $source_type (optional)
     * @param  string|null $sentiment (optional)
     * @param  string|null $content_gap (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitationGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCitationGroupsRequest($project_id, $view = 'url', $page = 1, $per_page = 20, $order = null, $direction = null, $model = null, $collection_id = null, $country_code = null, $language_code = null, $prompt = null, $from = null, $to = null, $query = null, $source_type = null, $sentiment = null, $content_gap = null, string $contentType = self::contentTypes['listCitationGroups'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling listCitationGroups'
            );
        }


        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling CitationIntelligenceApi.listCitationGroups, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling CitationIntelligenceApi.listCitationGroups, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling CitationIntelligenceApi.listCitationGroups, must be bigger than or equal to 1.');
        }
        














        $resourcePath = '/citation_intelligence/groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $view,
            'view', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $direction,
            'direction', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $model,
            'model', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $collection_id,
            'collection_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country_code,
            'country_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language_code,
            'language_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prompt,
            'prompt', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $source_type,
            'source_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sentiment,
            'sentiment', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $content_gap,
            'content_gap', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCitedUrlOccurrences
     *
     * Cited URL occurrences
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $per_page per_page (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitedUrlOccurrences'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function listCitedUrlOccurrences($project_id, $url_sha256, $page = 1, $per_page = 20, string $contentType = self::contentTypes['listCitedUrlOccurrences'][0])
    {
        $this->listCitedUrlOccurrencesWithHttpInfo($project_id, $url_sha256, $page, $per_page, $contentType);
    }

    /**
     * Operation listCitedUrlOccurrencesWithHttpInfo
     *
     * Cited URL occurrences
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitedUrlOccurrences'] to see the possible values for this operation
     *
     * @throws \LLMPulse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCitedUrlOccurrencesWithHttpInfo($project_id, $url_sha256, $page = 1, $per_page = 20, string $contentType = self::contentTypes['listCitedUrlOccurrences'][0])
    {
        $request = $this->listCitedUrlOccurrencesRequest($project_id, $url_sha256, $page, $per_page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LLMPulse\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCitedUrlOccurrencesAsync
     *
     * Cited URL occurrences
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitedUrlOccurrences'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitedUrlOccurrencesAsync($project_id, $url_sha256, $page = 1, $per_page = 20, string $contentType = self::contentTypes['listCitedUrlOccurrences'][0])
    {
        return $this->listCitedUrlOccurrencesAsyncWithHttpInfo($project_id, $url_sha256, $page, $per_page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCitedUrlOccurrencesAsyncWithHttpInfo
     *
     * Cited URL occurrences
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitedUrlOccurrences'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitedUrlOccurrencesAsyncWithHttpInfo($project_id, $url_sha256, $page = 1, $per_page = 20, string $contentType = self::contentTypes['listCitedUrlOccurrences'][0])
    {
        $returnType = '';
        $request = $this->listCitedUrlOccurrencesRequest($project_id, $url_sha256, $page, $per_page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCitedUrlOccurrences'
     *
     * @param  int $project_id Project ID (required)
     * @param  string $url_sha256 64-character hex SHA-256 of the cited URL (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCitedUrlOccurrences'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCitedUrlOccurrencesRequest($project_id, $url_sha256, $page = 1, $per_page = 20, string $contentType = self::contentTypes['listCitedUrlOccurrences'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling listCitedUrlOccurrences'
            );
        }

        // verify the required parameter 'url_sha256' is set
        if ($url_sha256 === null || (is_array($url_sha256) && count($url_sha256) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url_sha256 when calling listCitedUrlOccurrences'
            );
        }
        if (!preg_match("/^[a-f0-9]{64}$/", $url_sha256)) {
            throw new \InvalidArgumentException("invalid value for \"url_sha256\" when calling CitationIntelligenceApi.listCitedUrlOccurrences, must conform to the pattern /^[a-f0-9]{64}$/.");
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling CitationIntelligenceApi.listCitedUrlOccurrences, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling CitationIntelligenceApi.listCitedUrlOccurrences, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling CitationIntelligenceApi.listCitedUrlOccurrences, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/citation_intelligence/urls/{url_sha256}/occurrences';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($url_sha256 !== null) {
            $resourcePath = str_replace(
                '{url_sha256}',
                ObjectSerializer::toPathValue($url_sha256),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
