<?php
/**
 * CreateProjectDraftRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.49.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * CreateProjectDraftRequest Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateProjectDraftRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'createProjectDraft_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'website_url' => 'string',
        'main_country' => 'string',
        'main_language' => 'string',
        'use_subdomain' => 'bool',
        'suggest' => 'bool',
        'execute_prompts_immediately' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'website_url' => 'uri',
        'main_country' => null,
        'main_language' => null,
        'use_subdomain' => null,
        'suggest' => null,
        'execute_prompts_immediately' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'website_url' => false,
        'main_country' => false,
        'main_language' => false,
        'use_subdomain' => false,
        'suggest' => false,
        'execute_prompts_immediately' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'website_url' => 'website_url',
        'main_country' => 'main_country',
        'main_language' => 'main_language',
        'use_subdomain' => 'use_subdomain',
        'suggest' => 'suggest',
        'execute_prompts_immediately' => 'execute_prompts_immediately'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'website_url' => 'setWebsiteUrl',
        'main_country' => 'setMainCountry',
        'main_language' => 'setMainLanguage',
        'use_subdomain' => 'setUseSubdomain',
        'suggest' => 'setSuggest',
        'execute_prompts_immediately' => 'setExecutePromptsImmediately'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'website_url' => 'getWebsiteUrl',
        'main_country' => 'getMainCountry',
        'main_language' => 'getMainLanguage',
        'use_subdomain' => 'getUseSubdomain',
        'suggest' => 'getSuggest',
        'execute_prompts_immediately' => 'getExecutePromptsImmediately'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('website_url', $data ?? [], null);
        $this->setIfExists('main_country', $data ?? [], null);
        $this->setIfExists('main_language', $data ?? [], null);
        $this->setIfExists('use_subdomain', $data ?? [], false);
        $this->setIfExists('suggest', $data ?? [], true);
        $this->setIfExists('execute_prompts_immediately', $data ?? [], true);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['website_url'] === null) {
            $invalidProperties[] = "'website_url' can't be null";
        }
        if ($this->container['main_country'] === null) {
            $invalidProperties[] = "'main_country' can't be null";
        }
        if ($this->container['main_language'] === null) {
            $invalidProperties[] = "'main_language' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets website_url
     *
     * @return string
     */
    public function getWebsiteUrl()
    {
        return $this->container['website_url'];
    }

    /**
     * Sets website_url
     *
     * @param string $website_url Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
     *
     * @return self
     */
    public function setWebsiteUrl($website_url)
    {
        if (is_null($website_url)) {
            throw new \InvalidArgumentException('non-nullable website_url cannot be null');
        }
        $this->container['website_url'] = $website_url;

        return $this;
    }

    /**
     * Gets main_country
     *
     * @return string
     */
    public function getMainCountry()
    {
        return $this->container['main_country'];
    }

    /**
     * Sets main_country
     *
     * @param string $main_country main_country
     *
     * @return self
     */
    public function setMainCountry($main_country)
    {
        if (is_null($main_country)) {
            throw new \InvalidArgumentException('non-nullable main_country cannot be null');
        }
        $this->container['main_country'] = $main_country;

        return $this;
    }

    /**
     * Gets main_language
     *
     * @return string
     */
    public function getMainLanguage()
    {
        return $this->container['main_language'];
    }

    /**
     * Sets main_language
     *
     * @param string $main_language main_language
     *
     * @return self
     */
    public function setMainLanguage($main_language)
    {
        if (is_null($main_language)) {
            throw new \InvalidArgumentException('non-nullable main_language cannot be null');
        }
        $this->container['main_language'] = $main_language;

        return $this;
    }

    /**
     * Gets use_subdomain
     *
     * @return bool|null
     */
    public function getUseSubdomain()
    {
        return $this->container['use_subdomain'];
    }

    /**
     * Sets use_subdomain
     *
     * @param bool|null $use_subdomain use_subdomain
     *
     * @return self
     */
    public function setUseSubdomain($use_subdomain)
    {
        if (is_null($use_subdomain)) {
            throw new \InvalidArgumentException('non-nullable use_subdomain cannot be null');
        }
        $this->container['use_subdomain'] = $use_subdomain;

        return $this;
    }

    /**
     * Gets suggest
     *
     * @return bool|null
     */
    public function getSuggest()
    {
        return $this->container['suggest'];
    }

    /**
     * Sets suggest
     *
     * @param bool|null $suggest suggest
     *
     * @return self
     */
    public function setSuggest($suggest)
    {
        if (is_null($suggest)) {
            throw new \InvalidArgumentException('non-nullable suggest cannot be null');
        }
        $this->container['suggest'] = $suggest;

        return $this;
    }

    /**
     * Gets execute_prompts_immediately
     *
     * @return bool|null
     */
    public function getExecutePromptsImmediately()
    {
        return $this->container['execute_prompts_immediately'];
    }

    /**
     * Sets execute_prompts_immediately
     *
     * @param bool|null $execute_prompts_immediately execute_prompts_immediately
     *
     * @return self
     */
    public function setExecutePromptsImmediately($execute_prompts_immediately)
    {
        if (is_null($execute_prompts_immediately)) {
            throw new \InvalidArgumentException('non-nullable execute_prompts_immediately cannot be null');
        }
        $this->container['execute_prompts_immediately'] = $execute_prompts_immediately;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


