<?php
/**
 * GetAccount200ResponseLimits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * GetAccount200ResponseLimits Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAccount200ResponseLimits implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'getAccount_200_response_limits';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'prompts' => '\LLMPulse\Model\AccountQuota',
        'projects' => '\LLMPulse\Model\AccountQuota',
        'competitors_per_project' => '\LLMPulse\Model\AccountCapacity',
        'intelligence_tasks' => '\LLMPulse\Model\AccountQuota',
        'team_members' => '\LLMPulse\Model\AccountCapacity'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'prompts' => null,
        'projects' => null,
        'competitors_per_project' => null,
        'intelligence_tasks' => null,
        'team_members' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'prompts' => false,
        'projects' => false,
        'competitors_per_project' => false,
        'intelligence_tasks' => false,
        'team_members' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'prompts' => 'prompts',
        'projects' => 'projects',
        'competitors_per_project' => 'competitors_per_project',
        'intelligence_tasks' => 'intelligence_tasks',
        'team_members' => 'team_members'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'prompts' => 'setPrompts',
        'projects' => 'setProjects',
        'competitors_per_project' => 'setCompetitorsPerProject',
        'intelligence_tasks' => 'setIntelligenceTasks',
        'team_members' => 'setTeamMembers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'prompts' => 'getPrompts',
        'projects' => 'getProjects',
        'competitors_per_project' => 'getCompetitorsPerProject',
        'intelligence_tasks' => 'getIntelligenceTasks',
        'team_members' => 'getTeamMembers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('prompts', $data ?? [], null);
        $this->setIfExists('projects', $data ?? [], null);
        $this->setIfExists('competitors_per_project', $data ?? [], null);
        $this->setIfExists('intelligence_tasks', $data ?? [], null);
        $this->setIfExists('team_members', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets prompts
     *
     * @return \LLMPulse\Model\AccountQuota|null
     */
    public function getPrompts()
    {
        return $this->container['prompts'];
    }

    /**
     * Sets prompts
     *
     * @param \LLMPulse\Model\AccountQuota|null $prompts prompts
     *
     * @return self
     */
    public function setPrompts($prompts)
    {
        if (is_null($prompts)) {
            throw new \InvalidArgumentException('non-nullable prompts cannot be null');
        }
        $this->container['prompts'] = $prompts;

        return $this;
    }

    /**
     * Gets projects
     *
     * @return \LLMPulse\Model\AccountQuota|null
     */
    public function getProjects()
    {
        return $this->container['projects'];
    }

    /**
     * Sets projects
     *
     * @param \LLMPulse\Model\AccountQuota|null $projects projects
     *
     * @return self
     */
    public function setProjects($projects)
    {
        if (is_null($projects)) {
            throw new \InvalidArgumentException('non-nullable projects cannot be null');
        }
        $this->container['projects'] = $projects;

        return $this;
    }

    /**
     * Gets competitors_per_project
     *
     * @return \LLMPulse\Model\AccountCapacity|null
     */
    public function getCompetitorsPerProject()
    {
        return $this->container['competitors_per_project'];
    }

    /**
     * Sets competitors_per_project
     *
     * @param \LLMPulse\Model\AccountCapacity|null $competitors_per_project competitors_per_project
     *
     * @return self
     */
    public function setCompetitorsPerProject($competitors_per_project)
    {
        if (is_null($competitors_per_project)) {
            throw new \InvalidArgumentException('non-nullable competitors_per_project cannot be null');
        }
        $this->container['competitors_per_project'] = $competitors_per_project;

        return $this;
    }

    /**
     * Gets intelligence_tasks
     *
     * @return \LLMPulse\Model\AccountQuota|null
     */
    public function getIntelligenceTasks()
    {
        return $this->container['intelligence_tasks'];
    }

    /**
     * Sets intelligence_tasks
     *
     * @param \LLMPulse\Model\AccountQuota|null $intelligence_tasks intelligence_tasks
     *
     * @return self
     */
    public function setIntelligenceTasks($intelligence_tasks)
    {
        if (is_null($intelligence_tasks)) {
            throw new \InvalidArgumentException('non-nullable intelligence_tasks cannot be null');
        }
        $this->container['intelligence_tasks'] = $intelligence_tasks;

        return $this;
    }

    /**
     * Gets team_members
     *
     * @return \LLMPulse\Model\AccountCapacity|null
     */
    public function getTeamMembers()
    {
        return $this->container['team_members'];
    }

    /**
     * Sets team_members
     *
     * @param \LLMPulse\Model\AccountCapacity|null $team_members team_members
     *
     * @return self
     */
    public function setTeamMembers($team_members)
    {
        if (is_null($team_members)) {
            throw new \InvalidArgumentException('non-nullable team_members cannot be null');
        }
        $this->container['team_members'] = $team_members;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


