<?php
/**
 * IntelligenceTask
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * IntelligenceTask Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IntelligenceTask implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'IntelligenceTask';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'public_id' => 'string',
        'project_id' => 'int',
        'task_type' => 'string',
        'title' => 'string',
        'status' => 'string',
        'prompt_id' => 'int',
        'prompt_text' => 'string',
        'agentic_mode' => 'bool',
        'custom_topic' => 'string',
        'user_instructions' => 'string',
        'output_language_code' => 'string',
        'word_count' => 'int',
        'result_data' => 'object',
        'error_message' => 'string',
        'estimated_time' => 'string',
        'created_at' => '\DateTime',
        'processed_at' => '\DateTime',
        'request_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'public_id' => null,
        'project_id' => null,
        'task_type' => null,
        'title' => null,
        'status' => null,
        'prompt_id' => null,
        'prompt_text' => null,
        'agentic_mode' => null,
        'custom_topic' => null,
        'user_instructions' => null,
        'output_language_code' => null,
        'word_count' => null,
        'result_data' => null,
        'error_message' => null,
        'estimated_time' => null,
        'created_at' => 'date-time',
        'processed_at' => 'date-time',
        'request_id' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'public_id' => false,
        'project_id' => false,
        'task_type' => false,
        'title' => false,
        'status' => false,
        'prompt_id' => true,
        'prompt_text' => true,
        'agentic_mode' => false,
        'custom_topic' => true,
        'user_instructions' => true,
        'output_language_code' => true,
        'word_count' => true,
        'result_data' => false,
        'error_message' => true,
        'estimated_time' => true,
        'created_at' => false,
        'processed_at' => true,
        'request_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'public_id' => 'public_id',
        'project_id' => 'project_id',
        'task_type' => 'task_type',
        'title' => 'title',
        'status' => 'status',
        'prompt_id' => 'prompt_id',
        'prompt_text' => 'prompt_text',
        'agentic_mode' => 'agentic_mode',
        'custom_topic' => 'custom_topic',
        'user_instructions' => 'user_instructions',
        'output_language_code' => 'output_language_code',
        'word_count' => 'word_count',
        'result_data' => 'result_data',
        'error_message' => 'error_message',
        'estimated_time' => 'estimated_time',
        'created_at' => 'created_at',
        'processed_at' => 'processed_at',
        'request_id' => 'request_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'public_id' => 'setPublicId',
        'project_id' => 'setProjectId',
        'task_type' => 'setTaskType',
        'title' => 'setTitle',
        'status' => 'setStatus',
        'prompt_id' => 'setPromptId',
        'prompt_text' => 'setPromptText',
        'agentic_mode' => 'setAgenticMode',
        'custom_topic' => 'setCustomTopic',
        'user_instructions' => 'setUserInstructions',
        'output_language_code' => 'setOutputLanguageCode',
        'word_count' => 'setWordCount',
        'result_data' => 'setResultData',
        'error_message' => 'setErrorMessage',
        'estimated_time' => 'setEstimatedTime',
        'created_at' => 'setCreatedAt',
        'processed_at' => 'setProcessedAt',
        'request_id' => 'setRequestId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'public_id' => 'getPublicId',
        'project_id' => 'getProjectId',
        'task_type' => 'getTaskType',
        'title' => 'getTitle',
        'status' => 'getStatus',
        'prompt_id' => 'getPromptId',
        'prompt_text' => 'getPromptText',
        'agentic_mode' => 'getAgenticMode',
        'custom_topic' => 'getCustomTopic',
        'user_instructions' => 'getUserInstructions',
        'output_language_code' => 'getOutputLanguageCode',
        'word_count' => 'getWordCount',
        'result_data' => 'getResultData',
        'error_message' => 'getErrorMessage',
        'estimated_time' => 'getEstimatedTime',
        'created_at' => 'getCreatedAt',
        'processed_at' => 'getProcessedAt',
        'request_id' => 'getRequestId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('public_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('task_type', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('prompt_id', $data ?? [], null);
        $this->setIfExists('prompt_text', $data ?? [], null);
        $this->setIfExists('agentic_mode', $data ?? [], null);
        $this->setIfExists('custom_topic', $data ?? [], null);
        $this->setIfExists('user_instructions', $data ?? [], null);
        $this->setIfExists('output_language_code', $data ?? [], null);
        $this->setIfExists('word_count', $data ?? [], null);
        $this->setIfExists('result_data', $data ?? [], null);
        $this->setIfExists('error_message', $data ?? [], null);
        $this->setIfExists('estimated_time', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('processed_at', $data ?? [], null);
        $this->setIfExists('request_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets public_id
     *
     * @return string|null
     */
    public function getPublicId()
    {
        return $this->container['public_id'];
    }

    /**
     * Sets public_id
     *
     * @param string|null $public_id public_id
     *
     * @return self
     */
    public function setPublicId($public_id)
    {
        if (is_null($public_id)) {
            throw new \InvalidArgumentException('non-nullable public_id cannot be null');
        }
        $this->container['public_id'] = $public_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return int|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param int|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets task_type
     *
     * @return string|null
     */
    public function getTaskType()
    {
        return $this->container['task_type'];
    }

    /**
     * Sets task_type
     *
     * @param string|null $task_type task_type
     *
     * @return self
     */
    public function setTaskType($task_type)
    {
        if (is_null($task_type)) {
            throw new \InvalidArgumentException('non-nullable task_type cannot be null');
        }
        $this->container['task_type'] = $task_type;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets prompt_id
     *
     * @return int|null
     */
    public function getPromptId()
    {
        return $this->container['prompt_id'];
    }

    /**
     * Sets prompt_id
     *
     * @param int|null $prompt_id prompt_id
     *
     * @return self
     */
    public function setPromptId($prompt_id)
    {
        if (is_null($prompt_id)) {
            array_push($this->openAPINullablesSetToNull, 'prompt_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prompt_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prompt_id'] = $prompt_id;

        return $this;
    }

    /**
     * Gets prompt_text
     *
     * @return string|null
     */
    public function getPromptText()
    {
        return $this->container['prompt_text'];
    }

    /**
     * Sets prompt_text
     *
     * @param string|null $prompt_text prompt_text
     *
     * @return self
     */
    public function setPromptText($prompt_text)
    {
        if (is_null($prompt_text)) {
            array_push($this->openAPINullablesSetToNull, 'prompt_text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prompt_text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prompt_text'] = $prompt_text;

        return $this;
    }

    /**
     * Gets agentic_mode
     *
     * @return bool|null
     */
    public function getAgenticMode()
    {
        return $this->container['agentic_mode'];
    }

    /**
     * Sets agentic_mode
     *
     * @param bool|null $agentic_mode agentic_mode
     *
     * @return self
     */
    public function setAgenticMode($agentic_mode)
    {
        if (is_null($agentic_mode)) {
            throw new \InvalidArgumentException('non-nullable agentic_mode cannot be null');
        }
        $this->container['agentic_mode'] = $agentic_mode;

        return $this;
    }

    /**
     * Gets custom_topic
     *
     * @return string|null
     */
    public function getCustomTopic()
    {
        return $this->container['custom_topic'];
    }

    /**
     * Sets custom_topic
     *
     * @param string|null $custom_topic custom_topic
     *
     * @return self
     */
    public function setCustomTopic($custom_topic)
    {
        if (is_null($custom_topic)) {
            array_push($this->openAPINullablesSetToNull, 'custom_topic');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_topic', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_topic'] = $custom_topic;

        return $this;
    }

    /**
     * Gets user_instructions
     *
     * @return string|null
     */
    public function getUserInstructions()
    {
        return $this->container['user_instructions'];
    }

    /**
     * Sets user_instructions
     *
     * @param string|null $user_instructions user_instructions
     *
     * @return self
     */
    public function setUserInstructions($user_instructions)
    {
        if (is_null($user_instructions)) {
            array_push($this->openAPINullablesSetToNull, 'user_instructions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_instructions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_instructions'] = $user_instructions;

        return $this;
    }

    /**
     * Gets output_language_code
     *
     * @return string|null
     */
    public function getOutputLanguageCode()
    {
        return $this->container['output_language_code'];
    }

    /**
     * Sets output_language_code
     *
     * @param string|null $output_language_code output_language_code
     *
     * @return self
     */
    public function setOutputLanguageCode($output_language_code)
    {
        if (is_null($output_language_code)) {
            array_push($this->openAPINullablesSetToNull, 'output_language_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('output_language_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['output_language_code'] = $output_language_code;

        return $this;
    }

    /**
     * Gets word_count
     *
     * @return int|null
     */
    public function getWordCount()
    {
        return $this->container['word_count'];
    }

    /**
     * Sets word_count
     *
     * @param int|null $word_count word_count
     *
     * @return self
     */
    public function setWordCount($word_count)
    {
        if (is_null($word_count)) {
            array_push($this->openAPINullablesSetToNull, 'word_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('word_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['word_count'] = $word_count;

        return $this;
    }

    /**
     * Gets result_data
     *
     * @return object|null
     */
    public function getResultData()
    {
        return $this->container['result_data'];
    }

    /**
     * Sets result_data
     *
     * @param object|null $result_data Only present when status='completed'
     *
     * @return self
     */
    public function setResultData($result_data)
    {
        if (is_null($result_data)) {
            throw new \InvalidArgumentException('non-nullable result_data cannot be null');
        }
        $this->container['result_data'] = $result_data;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message error_message
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        if (is_null($error_message)) {
            array_push($this->openAPINullablesSetToNull, 'error_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('error_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets estimated_time
     *
     * @return string|null
     */
    public function getEstimatedTime()
    {
        return $this->container['estimated_time'];
    }

    /**
     * Sets estimated_time
     *
     * @param string|null $estimated_time estimated_time
     *
     * @return self
     */
    public function setEstimatedTime($estimated_time)
    {
        if (is_null($estimated_time)) {
            array_push($this->openAPINullablesSetToNull, 'estimated_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estimated_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estimated_time'] = $estimated_time;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets processed_at
     *
     * @return \DateTime|null
     */
    public function getProcessedAt()
    {
        return $this->container['processed_at'];
    }

    /**
     * Sets processed_at
     *
     * @param \DateTime|null $processed_at processed_at
     *
     * @return self
     */
    public function setProcessedAt($processed_at)
    {
        if (is_null($processed_at)) {
            array_push($this->openAPINullablesSetToNull, 'processed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['processed_at'] = $processed_at;

        return $this;
    }

    /**
     * Gets request_id
     *
     * @return string|null
     */
    public function getRequestId()
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id
     *
     * @param string|null $request_id request_id
     *
     * @return self
     */
    public function setRequestId($request_id)
    {
        if (is_null($request_id)) {
            throw new \InvalidArgumentException('non-nullable request_id cannot be null');
        }
        $this->container['request_id'] = $request_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


