<?php
/**
 * LlmsTxtTechnicalGeoReportResultData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.52.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * LlmsTxtTechnicalGeoReportResultData Class Doc Comment
 *
 * @category Class
 * @description The files and generation details once the report has completed; null before that
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LlmsTxtTechnicalGeoReportResultData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LlmsTxtTechnicalGeoReport_result_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'llms_txt_content' => 'string',
        'llms_full_txt_content' => 'string',
        'manually_edited_at' => '\DateTime',
        'content_version' => 'string',
        'original_llms_txt_content' => 'string',
        'original_llms_full_txt_content' => 'string',
        'crawl_data' => 'object',
        'metadata' => 'object',
        'pages_crawled' => 'int',
        'generation_time_ms' => 'int',
        'openai_tokens_used' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'llms_txt_content' => null,
        'llms_full_txt_content' => null,
        'manually_edited_at' => 'date-time',
        'content_version' => null,
        'original_llms_txt_content' => null,
        'original_llms_full_txt_content' => null,
        'crawl_data' => null,
        'metadata' => null,
        'pages_crawled' => null,
        'generation_time_ms' => null,
        'openai_tokens_used' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'llms_txt_content' => false,
        'llms_full_txt_content' => true,
        'manually_edited_at' => true,
        'content_version' => false,
        'original_llms_txt_content' => true,
        'original_llms_full_txt_content' => true,
        'crawl_data' => true,
        'metadata' => true,
        'pages_crawled' => true,
        'generation_time_ms' => true,
        'openai_tokens_used' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'llms_txt_content' => 'llms_txt_content',
        'llms_full_txt_content' => 'llms_full_txt_content',
        'manually_edited_at' => 'manually_edited_at',
        'content_version' => 'content_version',
        'original_llms_txt_content' => 'original_llms_txt_content',
        'original_llms_full_txt_content' => 'original_llms_full_txt_content',
        'crawl_data' => 'crawl_data',
        'metadata' => 'metadata',
        'pages_crawled' => 'pages_crawled',
        'generation_time_ms' => 'generation_time_ms',
        'openai_tokens_used' => 'openai_tokens_used'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'llms_txt_content' => 'setLlmsTxtContent',
        'llms_full_txt_content' => 'setLlmsFullTxtContent',
        'manually_edited_at' => 'setManuallyEditedAt',
        'content_version' => 'setContentVersion',
        'original_llms_txt_content' => 'setOriginalLlmsTxtContent',
        'original_llms_full_txt_content' => 'setOriginalLlmsFullTxtContent',
        'crawl_data' => 'setCrawlData',
        'metadata' => 'setMetadata',
        'pages_crawled' => 'setPagesCrawled',
        'generation_time_ms' => 'setGenerationTimeMs',
        'openai_tokens_used' => 'setOpenaiTokensUsed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'llms_txt_content' => 'getLlmsTxtContent',
        'llms_full_txt_content' => 'getLlmsFullTxtContent',
        'manually_edited_at' => 'getManuallyEditedAt',
        'content_version' => 'getContentVersion',
        'original_llms_txt_content' => 'getOriginalLlmsTxtContent',
        'original_llms_full_txt_content' => 'getOriginalLlmsFullTxtContent',
        'crawl_data' => 'getCrawlData',
        'metadata' => 'getMetadata',
        'pages_crawled' => 'getPagesCrawled',
        'generation_time_ms' => 'getGenerationTimeMs',
        'openai_tokens_used' => 'getOpenaiTokensUsed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('llms_txt_content', $data ?? [], null);
        $this->setIfExists('llms_full_txt_content', $data ?? [], null);
        $this->setIfExists('manually_edited_at', $data ?? [], null);
        $this->setIfExists('content_version', $data ?? [], null);
        $this->setIfExists('original_llms_txt_content', $data ?? [], null);
        $this->setIfExists('original_llms_full_txt_content', $data ?? [], null);
        $this->setIfExists('crawl_data', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('pages_crawled', $data ?? [], null);
        $this->setIfExists('generation_time_ms', $data ?? [], null);
        $this->setIfExists('openai_tokens_used', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets llms_txt_content
     *
     * @return string|null
     */
    public function getLlmsTxtContent()
    {
        return $this->container['llms_txt_content'];
    }

    /**
     * Sets llms_txt_content
     *
     * @param string|null $llms_txt_content Current llms.txt, manual edits included
     *
     * @return self
     */
    public function setLlmsTxtContent($llms_txt_content)
    {
        if (is_null($llms_txt_content)) {
            throw new \InvalidArgumentException('non-nullable llms_txt_content cannot be null');
        }
        $this->container['llms_txt_content'] = $llms_txt_content;

        return $this;
    }

    /**
     * Gets llms_full_txt_content
     *
     * @return string|null
     */
    public function getLlmsFullTxtContent()
    {
        return $this->container['llms_full_txt_content'];
    }

    /**
     * Sets llms_full_txt_content
     *
     * @param string|null $llms_full_txt_content Current llms-full.txt, manual edits included
     *
     * @return self
     */
    public function setLlmsFullTxtContent($llms_full_txt_content)
    {
        if (is_null($llms_full_txt_content)) {
            array_push($this->openAPINullablesSetToNull, 'llms_full_txt_content');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('llms_full_txt_content', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['llms_full_txt_content'] = $llms_full_txt_content;

        return $this;
    }

    /**
     * Gets manually_edited_at
     *
     * @return \DateTime|null
     */
    public function getManuallyEditedAt()
    {
        return $this->container['manually_edited_at'];
    }

    /**
     * Sets manually_edited_at
     *
     * @param \DateTime|null $manually_edited_at When the files were last edited by hand in the app, the API or MCP; null while they are as generated
     *
     * @return self
     */
    public function setManuallyEditedAt($manually_edited_at)
    {
        if (is_null($manually_edited_at)) {
            array_push($this->openAPINullablesSetToNull, 'manually_edited_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('manually_edited_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['manually_edited_at'] = $manually_edited_at;

        return $this;
    }

    /**
     * Gets content_version
     *
     * @return string|null
     */
    public function getContentVersion()
    {
        return $this->container['content_version'];
    }

    /**
     * Sets content_version
     *
     * @param string|null $content_version Send it back as content_version when editing the files. It changes on every save
     *
     * @return self
     */
    public function setContentVersion($content_version)
    {
        if (is_null($content_version)) {
            throw new \InvalidArgumentException('non-nullable content_version cannot be null');
        }
        $this->container['content_version'] = $content_version;

        return $this;
    }

    /**
     * Gets original_llms_txt_content
     *
     * @return string|null
     */
    public function getOriginalLlmsTxtContent()
    {
        return $this->container['original_llms_txt_content'];
    }

    /**
     * Sets original_llms_txt_content
     *
     * @param string|null $original_llms_txt_content The generated llms.txt, kept from the first manual edit; null while the files are as generated
     *
     * @return self
     */
    public function setOriginalLlmsTxtContent($original_llms_txt_content)
    {
        if (is_null($original_llms_txt_content)) {
            array_push($this->openAPINullablesSetToNull, 'original_llms_txt_content');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('original_llms_txt_content', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['original_llms_txt_content'] = $original_llms_txt_content;

        return $this;
    }

    /**
     * Gets original_llms_full_txt_content
     *
     * @return string|null
     */
    public function getOriginalLlmsFullTxtContent()
    {
        return $this->container['original_llms_full_txt_content'];
    }

    /**
     * Sets original_llms_full_txt_content
     *
     * @param string|null $original_llms_full_txt_content The generated llms-full.txt, kept from the first manual edit; null while the files are as generated
     *
     * @return self
     */
    public function setOriginalLlmsFullTxtContent($original_llms_full_txt_content)
    {
        if (is_null($original_llms_full_txt_content)) {
            array_push($this->openAPINullablesSetToNull, 'original_llms_full_txt_content');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('original_llms_full_txt_content', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['original_llms_full_txt_content'] = $original_llms_full_txt_content;

        return $this;
    }

    /**
     * Gets crawl_data
     *
     * @return object|null
     */
    public function getCrawlData()
    {
        return $this->container['crawl_data'];
    }

    /**
     * Sets crawl_data
     *
     * @param object|null $crawl_data crawl_data
     *
     * @return self
     */
    public function setCrawlData($crawl_data)
    {
        if (is_null($crawl_data)) {
            array_push($this->openAPINullablesSetToNull, 'crawl_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('crawl_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['crawl_data'] = $crawl_data;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object|null $metadata Generation details, including output_language_code, the language the files were written in
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets pages_crawled
     *
     * @return int|null
     */
    public function getPagesCrawled()
    {
        return $this->container['pages_crawled'];
    }

    /**
     * Sets pages_crawled
     *
     * @param int|null $pages_crawled pages_crawled
     *
     * @return self
     */
    public function setPagesCrawled($pages_crawled)
    {
        if (is_null($pages_crawled)) {
            array_push($this->openAPINullablesSetToNull, 'pages_crawled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pages_crawled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pages_crawled'] = $pages_crawled;

        return $this;
    }

    /**
     * Gets generation_time_ms
     *
     * @return int|null
     */
    public function getGenerationTimeMs()
    {
        return $this->container['generation_time_ms'];
    }

    /**
     * Sets generation_time_ms
     *
     * @param int|null $generation_time_ms generation_time_ms
     *
     * @return self
     */
    public function setGenerationTimeMs($generation_time_ms)
    {
        if (is_null($generation_time_ms)) {
            array_push($this->openAPINullablesSetToNull, 'generation_time_ms');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('generation_time_ms', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['generation_time_ms'] = $generation_time_ms;

        return $this;
    }

    /**
     * Gets openai_tokens_used
     *
     * @return int|null
     */
    public function getOpenaiTokensUsed()
    {
        return $this->container['openai_tokens_used'];
    }

    /**
     * Sets openai_tokens_used
     *
     * @param int|null $openai_tokens_used openai_tokens_used
     *
     * @return self
     */
    public function setOpenaiTokensUsed($openai_tokens_used)
    {
        if (is_null($openai_tokens_used)) {
            array_push($this->openAPINullablesSetToNull, 'openai_tokens_used');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('openai_tokens_used', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['openai_tokens_used'] = $openai_tokens_used;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


