<?php
/**
 * LocalBusiness
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * LocalBusiness Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LocalBusiness implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LocalBusiness';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'business_key' => 'string',
        'title' => 'string',
        'address' => 'string',
        'domain' => 'string',
        'url' => 'string',
        'phone' => 'string',
        'avg_rating' => 'float',
        'reviews' => 'int',
        'avg_position' => 'float',
        'prompts' => 'int',
        'appearances' => 'int',
        'is_client' => 'bool',
        'competitor_id' => 'int',
        'competitor_name' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'business_key' => null,
        'title' => null,
        'address' => null,
        'domain' => null,
        'url' => null,
        'phone' => null,
        'avg_rating' => null,
        'reviews' => null,
        'avg_position' => null,
        'prompts' => null,
        'appearances' => null,
        'is_client' => null,
        'competitor_id' => null,
        'competitor_name' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'business_key' => false,
        'title' => false,
        'address' => true,
        'domain' => true,
        'url' => true,
        'phone' => true,
        'avg_rating' => true,
        'reviews' => true,
        'avg_position' => true,
        'prompts' => false,
        'appearances' => false,
        'is_client' => false,
        'competitor_id' => true,
        'competitor_name' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'business_key' => 'business_key',
        'title' => 'title',
        'address' => 'address',
        'domain' => 'domain',
        'url' => 'url',
        'phone' => 'phone',
        'avg_rating' => 'avg_rating',
        'reviews' => 'reviews',
        'avg_position' => 'avg_position',
        'prompts' => 'prompts',
        'appearances' => 'appearances',
        'is_client' => 'is_client',
        'competitor_id' => 'competitor_id',
        'competitor_name' => 'competitor_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'business_key' => 'setBusinessKey',
        'title' => 'setTitle',
        'address' => 'setAddress',
        'domain' => 'setDomain',
        'url' => 'setUrl',
        'phone' => 'setPhone',
        'avg_rating' => 'setAvgRating',
        'reviews' => 'setReviews',
        'avg_position' => 'setAvgPosition',
        'prompts' => 'setPrompts',
        'appearances' => 'setAppearances',
        'is_client' => 'setIsClient',
        'competitor_id' => 'setCompetitorId',
        'competitor_name' => 'setCompetitorName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'business_key' => 'getBusinessKey',
        'title' => 'getTitle',
        'address' => 'getAddress',
        'domain' => 'getDomain',
        'url' => 'getUrl',
        'phone' => 'getPhone',
        'avg_rating' => 'getAvgRating',
        'reviews' => 'getReviews',
        'avg_position' => 'getAvgPosition',
        'prompts' => 'getPrompts',
        'appearances' => 'getAppearances',
        'is_client' => 'getIsClient',
        'competitor_id' => 'getCompetitorId',
        'competitor_name' => 'getCompetitorName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('business_key', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('avg_rating', $data ?? [], null);
        $this->setIfExists('reviews', $data ?? [], null);
        $this->setIfExists('avg_position', $data ?? [], null);
        $this->setIfExists('prompts', $data ?? [], null);
        $this->setIfExists('appearances', $data ?? [], null);
        $this->setIfExists('is_client', $data ?? [], null);
        $this->setIfExists('competitor_id', $data ?? [], null);
        $this->setIfExists('competitor_name', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets business_key
     *
     * @return string|null
     */
    public function getBusinessKey()
    {
        return $this->container['business_key'];
    }

    /**
     * Sets business_key
     *
     * @param string|null $business_key Stable grouping key: the lowercased name and address
     *
     * @return self
     */
    public function setBusinessKey($business_key)
    {
        if (is_null($business_key)) {
            throw new \InvalidArgumentException('non-nullable business_key cannot be null');
        }
        $this->container['business_key'] = $business_key;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            array_push($this->openAPINullablesSetToNull, 'address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            array_push($this->openAPINullablesSetToNull, 'domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets avg_rating
     *
     * @return float|null
     */
    public function getAvgRating()
    {
        return $this->container['avg_rating'];
    }

    /**
     * Sets avg_rating
     *
     * @param float|null $avg_rating avg_rating
     *
     * @return self
     */
    public function setAvgRating($avg_rating)
    {
        if (is_null($avg_rating)) {
            array_push($this->openAPINullablesSetToNull, 'avg_rating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avg_rating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avg_rating'] = $avg_rating;

        return $this;
    }

    /**
     * Gets reviews
     *
     * @return int|null
     */
    public function getReviews()
    {
        return $this->container['reviews'];
    }

    /**
     * Sets reviews
     *
     * @param int|null $reviews reviews
     *
     * @return self
     */
    public function setReviews($reviews)
    {
        if (is_null($reviews)) {
            array_push($this->openAPINullablesSetToNull, 'reviews');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reviews', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reviews'] = $reviews;

        return $this;
    }

    /**
     * Gets avg_position
     *
     * @return float|null
     */
    public function getAvgPosition()
    {
        return $this->container['avg_position'];
    }

    /**
     * Sets avg_position
     *
     * @param float|null $avg_position Average rank of the business in the answer's list (1 = first)
     *
     * @return self
     */
    public function setAvgPosition($avg_position)
    {
        if (is_null($avg_position)) {
            array_push($this->openAPINullablesSetToNull, 'avg_position');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avg_position', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avg_position'] = $avg_position;

        return $this;
    }

    /**
     * Gets prompts
     *
     * @return int|null
     */
    public function getPrompts()
    {
        return $this->container['prompts'];
    }

    /**
     * Sets prompts
     *
     * @param int|null $prompts prompts
     *
     * @return self
     */
    public function setPrompts($prompts)
    {
        if (is_null($prompts)) {
            throw new \InvalidArgumentException('non-nullable prompts cannot be null');
        }
        $this->container['prompts'] = $prompts;

        return $this;
    }

    /**
     * Gets appearances
     *
     * @return int|null
     */
    public function getAppearances()
    {
        return $this->container['appearances'];
    }

    /**
     * Sets appearances
     *
     * @param int|null $appearances appearances
     *
     * @return self
     */
    public function setAppearances($appearances)
    {
        if (is_null($appearances)) {
            throw new \InvalidArgumentException('non-nullable appearances cannot be null');
        }
        $this->container['appearances'] = $appearances;

        return $this;
    }

    /**
     * Gets is_client
     *
     * @return bool|null
     */
    public function getIsClient()
    {
        return $this->container['is_client'];
    }

    /**
     * Sets is_client
     *
     * @param bool|null $is_client is_client
     *
     * @return self
     */
    public function setIsClient($is_client)
    {
        if (is_null($is_client)) {
            throw new \InvalidArgumentException('non-nullable is_client cannot be null');
        }
        $this->container['is_client'] = $is_client;

        return $this;
    }

    /**
     * Gets competitor_id
     *
     * @return int|null
     */
    public function getCompetitorId()
    {
        return $this->container['competitor_id'];
    }

    /**
     * Sets competitor_id
     *
     * @param int|null $competitor_id competitor_id
     *
     * @return self
     */
    public function setCompetitorId($competitor_id)
    {
        if (is_null($competitor_id)) {
            array_push($this->openAPINullablesSetToNull, 'competitor_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('competitor_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['competitor_id'] = $competitor_id;

        return $this;
    }

    /**
     * Gets competitor_name
     *
     * @return string|null
     */
    public function getCompetitorName()
    {
        return $this->container['competitor_name'];
    }

    /**
     * Sets competitor_name
     *
     * @param string|null $competitor_name competitor_name
     *
     * @return self
     */
    public function setCompetitorName($competitor_name)
    {
        if (is_null($competitor_name)) {
            array_push($this->openAPINullablesSetToNull, 'competitor_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('competitor_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['competitor_name'] = $competitor_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


