<?php
/**
 * ProjectCreateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * ProjectCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ProjectCreateRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'website_url' => 'string',
        'name' => 'string',
        'main_country' => 'string',
        'main_language' => 'string',
        'brand_name' => 'string',
        'description' => 'string',
        'industry' => 'string[]',
        'matching_names' => 'string[]',
        'prompts' => 'string[]',
        'competitors' => '\LLMPulse\Model\ProjectCreateRequestCompetitorsInner[]',
        'owned_media' => '\LLMPulse\Model\ProjectCreateRequestOwnedMedia',
        'use_subdomain' => 'bool',
        'weekly_email_subscribed' => 'bool',
        'external_identifier' => 'string',
        'execute_prompts_immediately' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'website_url' => 'uri',
        'name' => null,
        'main_country' => null,
        'main_language' => null,
        'brand_name' => null,
        'description' => null,
        'industry' => null,
        'matching_names' => null,
        'prompts' => null,
        'competitors' => null,
        'owned_media' => null,
        'use_subdomain' => null,
        'weekly_email_subscribed' => null,
        'external_identifier' => null,
        'execute_prompts_immediately' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'website_url' => false,
        'name' => false,
        'main_country' => false,
        'main_language' => false,
        'brand_name' => false,
        'description' => false,
        'industry' => false,
        'matching_names' => false,
        'prompts' => false,
        'competitors' => false,
        'owned_media' => false,
        'use_subdomain' => false,
        'weekly_email_subscribed' => false,
        'external_identifier' => false,
        'execute_prompts_immediately' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'website_url' => 'website_url',
        'name' => 'name',
        'main_country' => 'main_country',
        'main_language' => 'main_language',
        'brand_name' => 'brand_name',
        'description' => 'description',
        'industry' => 'industry',
        'matching_names' => 'matching_names',
        'prompts' => 'prompts',
        'competitors' => 'competitors',
        'owned_media' => 'owned_media',
        'use_subdomain' => 'use_subdomain',
        'weekly_email_subscribed' => 'weekly_email_subscribed',
        'external_identifier' => 'external_identifier',
        'execute_prompts_immediately' => 'execute_prompts_immediately'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'website_url' => 'setWebsiteUrl',
        'name' => 'setName',
        'main_country' => 'setMainCountry',
        'main_language' => 'setMainLanguage',
        'brand_name' => 'setBrandName',
        'description' => 'setDescription',
        'industry' => 'setIndustry',
        'matching_names' => 'setMatchingNames',
        'prompts' => 'setPrompts',
        'competitors' => 'setCompetitors',
        'owned_media' => 'setOwnedMedia',
        'use_subdomain' => 'setUseSubdomain',
        'weekly_email_subscribed' => 'setWeeklyEmailSubscribed',
        'external_identifier' => 'setExternalIdentifier',
        'execute_prompts_immediately' => 'setExecutePromptsImmediately'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'website_url' => 'getWebsiteUrl',
        'name' => 'getName',
        'main_country' => 'getMainCountry',
        'main_language' => 'getMainLanguage',
        'brand_name' => 'getBrandName',
        'description' => 'getDescription',
        'industry' => 'getIndustry',
        'matching_names' => 'getMatchingNames',
        'prompts' => 'getPrompts',
        'competitors' => 'getCompetitors',
        'owned_media' => 'getOwnedMedia',
        'use_subdomain' => 'getUseSubdomain',
        'weekly_email_subscribed' => 'getWeeklyEmailSubscribed',
        'external_identifier' => 'getExternalIdentifier',
        'execute_prompts_immediately' => 'getExecutePromptsImmediately'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('website_url', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('main_country', $data ?? [], null);
        $this->setIfExists('main_language', $data ?? [], null);
        $this->setIfExists('brand_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('industry', $data ?? [], null);
        $this->setIfExists('matching_names', $data ?? [], null);
        $this->setIfExists('prompts', $data ?? [], null);
        $this->setIfExists('competitors', $data ?? [], null);
        $this->setIfExists('owned_media', $data ?? [], null);
        $this->setIfExists('use_subdomain', $data ?? [], false);
        $this->setIfExists('weekly_email_subscribed', $data ?? [], false);
        $this->setIfExists('external_identifier', $data ?? [], null);
        $this->setIfExists('execute_prompts_immediately', $data ?? [], true);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['website_url'] === null) {
            $invalidProperties[] = "'website_url' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['main_country'] === null) {
            $invalidProperties[] = "'main_country' can't be null";
        }
        if ($this->container['main_language'] === null) {
            $invalidProperties[] = "'main_language' can't be null";
        }
        if (!is_null($this->container['prompts']) && (count($this->container['prompts']) > 100)) {
            $invalidProperties[] = "invalid value for 'prompts', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['external_identifier']) && !preg_match("/^[a-z0-9_-]{1,64}$/", $this->container['external_identifier'])) {
            $invalidProperties[] = "invalid value for 'external_identifier', must be conform to the pattern /^[a-z0-9_-]{1,64}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets website_url
     *
     * @return string
     */
    public function getWebsiteUrl()
    {
        return $this->container['website_url'];
    }

    /**
     * Sets website_url
     *
     * @param string $website_url Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
     *
     * @return self
     */
    public function setWebsiteUrl($website_url)
    {
        if (is_null($website_url)) {
            throw new \InvalidArgumentException('non-nullable website_url cannot be null');
        }
        $this->container['website_url'] = $website_url;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets main_country
     *
     * @return string
     */
    public function getMainCountry()
    {
        return $this->container['main_country'];
    }

    /**
     * Sets main_country
     *
     * @param string $main_country main_country
     *
     * @return self
     */
    public function setMainCountry($main_country)
    {
        if (is_null($main_country)) {
            throw new \InvalidArgumentException('non-nullable main_country cannot be null');
        }
        $this->container['main_country'] = $main_country;

        return $this;
    }

    /**
     * Gets main_language
     *
     * @return string
     */
    public function getMainLanguage()
    {
        return $this->container['main_language'];
    }

    /**
     * Sets main_language
     *
     * @param string $main_language main_language
     *
     * @return self
     */
    public function setMainLanguage($main_language)
    {
        if (is_null($main_language)) {
            throw new \InvalidArgumentException('non-nullable main_language cannot be null');
        }
        $this->container['main_language'] = $main_language;

        return $this;
    }

    /**
     * Gets brand_name
     *
     * @return string|null
     */
    public function getBrandName()
    {
        return $this->container['brand_name'];
    }

    /**
     * Sets brand_name
     *
     * @param string|null $brand_name brand_name
     *
     * @return self
     */
    public function setBrandName($brand_name)
    {
        if (is_null($brand_name)) {
            throw new \InvalidArgumentException('non-nullable brand_name cannot be null');
        }
        $this->container['brand_name'] = $brand_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets industry
     *
     * @return string[]|null
     */
    public function getIndustry()
    {
        return $this->container['industry'];
    }

    /**
     * Sets industry
     *
     * @param string[]|null $industry industry
     *
     * @return self
     */
    public function setIndustry($industry)
    {
        if (is_null($industry)) {
            throw new \InvalidArgumentException('non-nullable industry cannot be null');
        }
        $this->container['industry'] = $industry;

        return $this;
    }

    /**
     * Gets matching_names
     *
     * @return string[]|null
     */
    public function getMatchingNames()
    {
        return $this->container['matching_names'];
    }

    /**
     * Sets matching_names
     *
     * @param string[]|null $matching_names matching_names
     *
     * @return self
     */
    public function setMatchingNames($matching_names)
    {
        if (is_null($matching_names)) {
            throw new \InvalidArgumentException('non-nullable matching_names cannot be null');
        }
        $this->container['matching_names'] = $matching_names;

        return $this;
    }

    /**
     * Gets prompts
     *
     * @return string[]|null
     */
    public function getPrompts()
    {
        return $this->container['prompts'];
    }

    /**
     * Sets prompts
     *
     * @param string[]|null $prompts prompts
     *
     * @return self
     */
    public function setPrompts($prompts)
    {
        if (is_null($prompts)) {
            throw new \InvalidArgumentException('non-nullable prompts cannot be null');
        }
        if ((count($prompts) > 100)) {
            throw new \InvalidArgumentException('invalid value for $prompts when calling ProjectCreateRequest., number of items must be less than or equal to 100.');
        }
        $this->container['prompts'] = $prompts;

        return $this;
    }

    /**
     * Gets competitors
     *
     * @return \LLMPulse\Model\ProjectCreateRequestCompetitorsInner[]|null
     */
    public function getCompetitors()
    {
        return $this->container['competitors'];
    }

    /**
     * Sets competitors
     *
     * @param \LLMPulse\Model\ProjectCreateRequestCompetitorsInner[]|null $competitors competitors
     *
     * @return self
     */
    public function setCompetitors($competitors)
    {
        if (is_null($competitors)) {
            throw new \InvalidArgumentException('non-nullable competitors cannot be null');
        }
        $this->container['competitors'] = $competitors;

        return $this;
    }

    /**
     * Gets owned_media
     *
     * @return \LLMPulse\Model\ProjectCreateRequestOwnedMedia|null
     */
    public function getOwnedMedia()
    {
        return $this->container['owned_media'];
    }

    /**
     * Sets owned_media
     *
     * @param \LLMPulse\Model\ProjectCreateRequestOwnedMedia|null $owned_media owned_media
     *
     * @return self
     */
    public function setOwnedMedia($owned_media)
    {
        if (is_null($owned_media)) {
            throw new \InvalidArgumentException('non-nullable owned_media cannot be null');
        }
        $this->container['owned_media'] = $owned_media;

        return $this;
    }

    /**
     * Gets use_subdomain
     *
     * @return bool|null
     */
    public function getUseSubdomain()
    {
        return $this->container['use_subdomain'];
    }

    /**
     * Sets use_subdomain
     *
     * @param bool|null $use_subdomain use_subdomain
     *
     * @return self
     */
    public function setUseSubdomain($use_subdomain)
    {
        if (is_null($use_subdomain)) {
            throw new \InvalidArgumentException('non-nullable use_subdomain cannot be null');
        }
        $this->container['use_subdomain'] = $use_subdomain;

        return $this;
    }

    /**
     * Gets weekly_email_subscribed
     *
     * @return bool|null
     */
    public function getWeeklyEmailSubscribed()
    {
        return $this->container['weekly_email_subscribed'];
    }

    /**
     * Sets weekly_email_subscribed
     *
     * @param bool|null $weekly_email_subscribed weekly_email_subscribed
     *
     * @return self
     */
    public function setWeeklyEmailSubscribed($weekly_email_subscribed)
    {
        if (is_null($weekly_email_subscribed)) {
            throw new \InvalidArgumentException('non-nullable weekly_email_subscribed cannot be null');
        }
        $this->container['weekly_email_subscribed'] = $weekly_email_subscribed;

        return $this;
    }

    /**
     * Gets external_identifier
     *
     * @return string|null
     */
    public function getExternalIdentifier()
    {
        return $this->container['external_identifier'];
    }

    /**
     * Sets external_identifier
     *
     * @param string|null $external_identifier Embed-enabled (Enterprise) accounts only; other accounts receive ERR_PLAN_REQUIRED. Idempotency key and embed-session join key, unique per account
     *
     * @return self
     */
    public function setExternalIdentifier($external_identifier)
    {
        if (is_null($external_identifier)) {
            throw new \InvalidArgumentException('non-nullable external_identifier cannot be null');
        }

        if ((!preg_match("/^[a-z0-9_-]{1,64}$/", ObjectSerializer::toString($external_identifier)))) {
            throw new \InvalidArgumentException("invalid value for \$external_identifier when calling ProjectCreateRequest., must conform to the pattern /^[a-z0-9_-]{1,64}$/.");
        }

        $this->container['external_identifier'] = $external_identifier;

        return $this;
    }

    /**
     * Gets execute_prompts_immediately
     *
     * @return bool|null
     */
    public function getExecutePromptsImmediately()
    {
        return $this->container['execute_prompts_immediately'];
    }

    /**
     * Sets execute_prompts_immediately
     *
     * @param bool|null $execute_prompts_immediately execute_prompts_immediately
     *
     * @return self
     */
    public function setExecutePromptsImmediately($execute_prompts_immediately)
    {
        if (is_null($execute_prompts_immediately)) {
            throw new \InvalidArgumentException('non-nullable execute_prompts_immediately cannot be null');
        }
        $this->container['execute_prompts_immediately'] = $execute_prompts_immediately;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


