<?php
/**
 * ProjectCreateRequestOwnedMedia
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LLMPulse\Model;

use \ArrayAccess;
use \LLMPulse\ObjectSerializer;

/**
 * ProjectCreateRequestOwnedMedia Class Doc Comment
 *
 * @category Class
 * @description Requires Growth plan or above
 * @package  LLMPulse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectCreateRequestOwnedMedia implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ProjectCreateRequest_owned_media';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'youtube_channel_url' => 'string',
        'instagram_profile_url' => 'string',
        'facebook_page_url' => 'string',
        'tiktok_profile_url' => 'string',
        'app_store_url' => 'string',
        'google_play_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'youtube_channel_url' => null,
        'instagram_profile_url' => null,
        'facebook_page_url' => null,
        'tiktok_profile_url' => null,
        'app_store_url' => null,
        'google_play_url' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'youtube_channel_url' => false,
        'instagram_profile_url' => false,
        'facebook_page_url' => false,
        'tiktok_profile_url' => false,
        'app_store_url' => false,
        'google_play_url' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'youtube_channel_url' => 'youtube_channel_url',
        'instagram_profile_url' => 'instagram_profile_url',
        'facebook_page_url' => 'facebook_page_url',
        'tiktok_profile_url' => 'tiktok_profile_url',
        'app_store_url' => 'app_store_url',
        'google_play_url' => 'google_play_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'youtube_channel_url' => 'setYoutubeChannelUrl',
        'instagram_profile_url' => 'setInstagramProfileUrl',
        'facebook_page_url' => 'setFacebookPageUrl',
        'tiktok_profile_url' => 'setTiktokProfileUrl',
        'app_store_url' => 'setAppStoreUrl',
        'google_play_url' => 'setGooglePlayUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'youtube_channel_url' => 'getYoutubeChannelUrl',
        'instagram_profile_url' => 'getInstagramProfileUrl',
        'facebook_page_url' => 'getFacebookPageUrl',
        'tiktok_profile_url' => 'getTiktokProfileUrl',
        'app_store_url' => 'getAppStoreUrl',
        'google_play_url' => 'getGooglePlayUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('youtube_channel_url', $data ?? [], null);
        $this->setIfExists('instagram_profile_url', $data ?? [], null);
        $this->setIfExists('facebook_page_url', $data ?? [], null);
        $this->setIfExists('tiktok_profile_url', $data ?? [], null);
        $this->setIfExists('app_store_url', $data ?? [], null);
        $this->setIfExists('google_play_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets youtube_channel_url
     *
     * @return string|null
     */
    public function getYoutubeChannelUrl()
    {
        return $this->container['youtube_channel_url'];
    }

    /**
     * Sets youtube_channel_url
     *
     * @param string|null $youtube_channel_url youtube_channel_url
     *
     * @return self
     */
    public function setYoutubeChannelUrl($youtube_channel_url)
    {
        if (is_null($youtube_channel_url)) {
            throw new \InvalidArgumentException('non-nullable youtube_channel_url cannot be null');
        }
        $this->container['youtube_channel_url'] = $youtube_channel_url;

        return $this;
    }

    /**
     * Gets instagram_profile_url
     *
     * @return string|null
     */
    public function getInstagramProfileUrl()
    {
        return $this->container['instagram_profile_url'];
    }

    /**
     * Sets instagram_profile_url
     *
     * @param string|null $instagram_profile_url instagram_profile_url
     *
     * @return self
     */
    public function setInstagramProfileUrl($instagram_profile_url)
    {
        if (is_null($instagram_profile_url)) {
            throw new \InvalidArgumentException('non-nullable instagram_profile_url cannot be null');
        }
        $this->container['instagram_profile_url'] = $instagram_profile_url;

        return $this;
    }

    /**
     * Gets facebook_page_url
     *
     * @return string|null
     */
    public function getFacebookPageUrl()
    {
        return $this->container['facebook_page_url'];
    }

    /**
     * Sets facebook_page_url
     *
     * @param string|null $facebook_page_url facebook_page_url
     *
     * @return self
     */
    public function setFacebookPageUrl($facebook_page_url)
    {
        if (is_null($facebook_page_url)) {
            throw new \InvalidArgumentException('non-nullable facebook_page_url cannot be null');
        }
        $this->container['facebook_page_url'] = $facebook_page_url;

        return $this;
    }

    /**
     * Gets tiktok_profile_url
     *
     * @return string|null
     */
    public function getTiktokProfileUrl()
    {
        return $this->container['tiktok_profile_url'];
    }

    /**
     * Sets tiktok_profile_url
     *
     * @param string|null $tiktok_profile_url tiktok_profile_url
     *
     * @return self
     */
    public function setTiktokProfileUrl($tiktok_profile_url)
    {
        if (is_null($tiktok_profile_url)) {
            throw new \InvalidArgumentException('non-nullable tiktok_profile_url cannot be null');
        }
        $this->container['tiktok_profile_url'] = $tiktok_profile_url;

        return $this;
    }

    /**
     * Gets app_store_url
     *
     * @return string|null
     */
    public function getAppStoreUrl()
    {
        return $this->container['app_store_url'];
    }

    /**
     * Sets app_store_url
     *
     * @param string|null $app_store_url app_store_url
     *
     * @return self
     */
    public function setAppStoreUrl($app_store_url)
    {
        if (is_null($app_store_url)) {
            throw new \InvalidArgumentException('non-nullable app_store_url cannot be null');
        }
        $this->container['app_store_url'] = $app_store_url;

        return $this;
    }

    /**
     * Gets google_play_url
     *
     * @return string|null
     */
    public function getGooglePlayUrl()
    {
        return $this->container['google_play_url'];
    }

    /**
     * Sets google_play_url
     *
     * @param string|null $google_play_url google_play_url
     *
     * @return self
     */
    public function setGooglePlayUrl($google_play_url)
    {
        if (is_null($google_play_url)) {
            throw new \InvalidArgumentException('non-nullable google_play_url cannot be null');
        }
        $this->container['google_play_url'] = $google_play_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


